services:
  db:
    image: rsp-courses-db:18
    build:
      context: ./db
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: rsp_courses
      POSTGRES_USER: postgres
      POSTGRES_INITDB_ARGS: >-
        --encoding=UTF8
        --locale=ru_RU.UTF-8
        --auth-host=scram-sha-256
        --auth-local=scram-sha-256
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rsp_courses"]
      interval: 2s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  app:
    image: rsp-courses-app:1.0.0
    build:
      context: ./app
    environment:
      LOG_FILE: ${LOG_FILE:-/logs/course-app.log}
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
    volumes:
      - app-logs:/logs

volumes:
  postgres-data:
  app-logs:
